{
 "title": "hemera",
 "description": "Prometheus Blackbox & Whitebox Exporter",
 "tags": [
  "blackbox",
  "whitebox",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success, target)"
    }
   },
   {
    "name": "phase",
    "label": "HTTP phase",
    "query": {
     "query": "label_values(probe_http_duration_seconds, phase)"
    }
   },
   {
    "name": "client",
    "query": {
     "query": "label_values(tun_probe_success, client)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(tun_probe_success,protocol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Probe Live",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{target=~\"$target\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Probe Tunnels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tun_probe_success{client=~\"$client\"}",
     "legendFormat": "{{protocol}}/{{client}}"
    }
   ]
  },
  {
   "title": "Probe Live Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$target\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Probe Tunnels Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tun_probe_duration_seconds{client=~\"$client\"}",
     "legendFormat": "{{protocol}}/{{client}} -> {{target}}"
    }
   ]
  },
  {
   "title": "HTTP Duration (phase = $phase)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{target=~\"$target\", phase=~\"$phase\"}",
     "legendFormat": "{{target}} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Live Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{target=~\"$target\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Tunnels Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tun_probe_success{client=~\"$client\"}",
     "legendFormat": "{{protocol}}/{{client}}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$target\"}) by (target)",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "avg(tun_probe_duration_seconds{client=~\"$client\", protocol=~\"$protocol\"}) by (client, protocol)",
     "legendFormat": "{{protocol}}/{{client}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$target\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}